### ISSUE TITLE
Best way to get syntax highlighting?

### ISSUE THREAD

**Issue by LordMZTE** [vantreeseba/coc-haxe#15]
What's the best plugin to use together with coc-haxe in order to get syntax highlighting? Is it a good idea to use it together with vaxe, or should I use vim-haxe instead?

**Comment by vantreeseba** [comment]
Hi, currently it does not support syntax highlighting through the language server, so I think something like vim-haxe is the best way to go.

I've been looking into / starting on a tree-sitter parser for haxe as well, but progress is slow.

**Comment by LordMZTE** [comment]
Ah, I see. Well, vim-haxe unfortunately looks pretty outdated, and I currently get my haxe syntax highlighting with vim-polyglot, but it's not that great. If you are going to make a haxe syntax plugin, I'd definitely consider using it. Thanks for your reply!

**Comment by vantreeseba** [comment]
I pushed up what I have so far onto this repo, and you're welcome to test it.

It is still very much in a "it mostly works, but will probably not work very well yet" stage.
https://github.com/vantreeseba/tree-sitter-haxe
