### ISSUE TITLE
More than 10 hxml files

### ISSUE THREAD

**Issue by neimanpinchas** [vantreeseba/coc-haxe#24]
I have a project with more than 10 hxml files (client, server, micro-services , tests etc)

When I am working with nvim I am unable to change hxml greater than 9, because when I press 1 the first is selected.\

My current work around is to rename the wanted hxml file and prepend a_ to the name so it becomes first in alphabetical order.

Is there any way to change hxml without the dialog?

or what would take to implement a timer? require enter?

or maybe if there is more than 9 just display a message with a input box afterwards

**Comment by vantreeseba** [comment]
Hmm, I can make a command that will let you set it via typing it in vs the dialog, that's how it was previously so that should fix it for now.

Notes for self:
I'll think about this more, perhaps the COC dialog is being weird or used incorrectly.

**Comment by neimanpinchas** [comment]
I've just checked the code.
I see this line `workspace.getConfiguration('haxe').update('hxml', hxml);`

Is possible to run this somehow from command mode as a temporary workarround?

**Comment by vantreeseba** [comment]
Sorry I've been super busy with life, but this is still on my radar.
I will make a test project and see what works best for this.

**Comment by vantreeseba** [comment]
This should be closed, I changed it to a list that is "filterable" by the filename, and should behave much better.

Let me know if this is still an issue for you after 0.19.0
