### ISSUE TITLE
Can `build.hxml` be looked recursively in parent dirs?

### ISSUE THREAD

**Issue by emugel** [vantreeseba/coc-haxe#3]
Hi there! It's nice to see a haxe plugin for coc being developed.
I come from https://github.com/vshaxe/vshaxe/issues/412, I'll just repost my question here and since you are also a vim + coc + haxe user you can tell me if you also have this problem.

Let's say our project is just:

```
build.hxml
src/Main.hx
```

To launch vim, if I do `vim src/Main.hx`, completion works.
If I do, `cd src ; vim Main.hx`, it doesn't.

The nvim-coc plugins :CocInfo reveals it's simply because in the second case, the `build.hxml` is searched in `src/build.hxml`!

Do you have the same problem or is it just me? 

I'm not using your plugin yet, I'm planning to; so let's say it's a way to engage the conversation with a feature that I would like to see implemented (search parent dirs for a file named `build.hxml`, that or another way).

**Comment by emugel** [comment]
This might be related: https://github.com/neoclide/coc.nvim/issues/107

**Comment by vantreeseba** [comment]
Look into https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

This should be being applied, it may not be in langclient code.

**Comment by vantreeseba** [comment]
This should be working, the root pattern contribution in the package.json should apply and it seems to be working for me even without a .git folder.

Closing for now.

**Comment by vantreeseba** [comment]
If this is not working for you, ensure that .hx files are set to use filetype 'haxe'.
