### ISSUE TITLE
Setting module path seems not to work?

### ISSUE THREAD

**Issue by vantreeseba** [vantreeseba/coc-haxe#5]
![image](https://user-images.githubusercontent.com/316782/85649413-c0757a80-b668-11ea-835b-86d56c85d38c.png)

**Comment by vantreeseba** [comment]
It seems like everything but completion is working.

**Comment by kLabz** [comment]
> It seems like everything but completion is working.

Yeah that does seem like the issue I was having too.

> Can you attach the coc log or the info if there are errors occuring?

I can't do that atm, sorry. Will do later if it still helps, but seems like you managed to reproduce

**Comment by vantreeseba** [comment]
Ok, thanks!

Yeah if we're having the same symptoms then don't worry about logs.

**Comment by vantreeseba** [comment]
For myself, this seems to be related to something in the haxe language server, not sure why this is occuring, but reverting to 0.4.0 with the bin at the point everything works fine.

**Comment by kLabz** [comment]
Do you know from which version of haxe lsp this one was from?

**Comment by vantreeseba** [comment]
0.4.0 was publish on June 4, so I did pull a lsp commit from before then and it worked fine, so I'm assuming there is some change since that works fine with vscode but coc isn't dealing with in the same way.

**Comment by kLabz** [comment]
Ok, I'll try to find the commit you used and what changed since then.

Do you mind if the process to write bin/server.js changes so that it's easier to know where it's from and to update it? There's already a build process anyway :)

**Comment by kLabz** [comment]
How did you build it? I fail to get a similar output =/

**Comment by vantreeseba** [comment]
I'm down for anything with a pull-request, atm I build the bin/server.js by hand and copy it over from LSP.
The build steps are on their repo (i.e. the lix stuff).

I'm not 100% sure what you mean by 
> Do you mind if the process to write bin/server.js changes so that it's easier to know where it's from and to update it? There's already a build process anyway :)

Do you mean when I commit those changes, add something to the comment marking what commit of the LSP repo it came from or etc?
